defaults: &defaults
  rabbitmq_url: <%= ENV['rabbitmq_url'] || "amqp://rabbit:rabbit@localhost:5672/dev" %>
  rabbitmq_api_url: <%= ENV['rabbitmq_api_url'] || "http://guest:guest@localhost:15672" %>  
  aws:
    access_key_id: AKIAIWMNME76CRB3GGXA
    secret_access_key: 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
  notification:
    host_url: <%= ENV['NOTIFICATION_HOST_URL'] || 'https://notifications.kyck.dev' %>
    path_name: <%= ENV['NOTIFICATION_PATH'] || '/api/v1/notifications.json' %>
    stomp_url: <%= ENV['NOTIFICATION_STOMP_URL'] || 'https://localhost:15675/stomp' %>
    stomp_host: <%= ENV['NOTIFICATION_STOMP_HOST'] || 'dev' %>    

development:
  <<: *defaults
  rabbitmq_vhost: 'dev'  


staging:
  <<: *defaults
  rabbitmq_vhost: 'staging'

test:
  <<: *defaults
  rabbitmq_vhost: 'test'  

production:
  <<: *defaults
  rabbitmq_vhost: '/'  